# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/hartley/Documents/School/fall2025/CS460/Chagalite-Interpreter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/hartley/Documents/School/fall2025/CS460/Chagalite-Interpreter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/hartley/Documents/School/fall2025/CS460/Chagalite-Interpreter/CMakeFiles /mnt/c/Users/hartley/Documents/School/fall2025/CS460/Chagalite-Interpreter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/hartley/Documents/School/fall2025/CS460/Chagalite-Interpreter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.x

# Build rule for target.
main.x: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main.x
.PHONY : main.x

# fast build rule for target.
main.x/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/build
.PHONY : main.x/fast

AST.o: AST.cpp.o
.PHONY : AST.o

# target to build an object file
AST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/AST.cpp.o
.PHONY : AST.cpp.o

AST.i: AST.cpp.i
.PHONY : AST.i

# target to preprocess a source file
AST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/AST.cpp.i
.PHONY : AST.cpp.i

AST.s: AST.cpp.s
.PHONY : AST.s

# target to generate assembly for a file
AST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/AST.cpp.s
.PHONY : AST.cpp.s

LCRS.o: LCRS.cpp.o
.PHONY : LCRS.o

# target to build an object file
LCRS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/LCRS.cpp.o
.PHONY : LCRS.cpp.o

LCRS.i: LCRS.cpp.i
.PHONY : LCRS.i

# target to preprocess a source file
LCRS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/LCRS.cpp.i
.PHONY : LCRS.cpp.i

LCRS.s: LCRS.cpp.s
.PHONY : LCRS.s

# target to generate assembly for a file
LCRS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/LCRS.cpp.s
.PHONY : LCRS.cpp.s

STLL.o: STLL.cpp.o
.PHONY : STLL.o

# target to build an object file
STLL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/STLL.cpp.o
.PHONY : STLL.cpp.o

STLL.i: STLL.cpp.i
.PHONY : STLL.i

# target to preprocess a source file
STLL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/STLL.cpp.i
.PHONY : STLL.cpp.i

STLL.s: STLL.cpp.s
.PHONY : STLL.s

# target to generate assembly for a file
STLL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/STLL.cpp.s
.PHONY : STLL.cpp.s

linkedlist.o: linkedlist.cpp.o
.PHONY : linkedlist.o

# target to build an object file
linkedlist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/linkedlist.cpp.o
.PHONY : linkedlist.cpp.o

linkedlist.i: linkedlist.cpp.i
.PHONY : linkedlist.i

# target to preprocess a source file
linkedlist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/linkedlist.cpp.i
.PHONY : linkedlist.cpp.i

linkedlist.s: linkedlist.cpp.s
.PHONY : linkedlist.s

# target to generate assembly for a file
linkedlist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/linkedlist.cpp.s
.PHONY : linkedlist.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.x.dir/build.make CMakeFiles/main.x.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main.x"
	@echo "... AST.o"
	@echo "... AST.i"
	@echo "... AST.s"
	@echo "... LCRS.o"
	@echo "... LCRS.i"
	@echo "... LCRS.s"
	@echo "... STLL.o"
	@echo "... STLL.i"
	@echo "... STLL.s"
	@echo "... linkedlist.o"
	@echo "... linkedlist.i"
	@echo "... linkedlist.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

